-- Тест 009: Работа со сложными вложениями
-- Этот тест проверяет корректность работы при сложном вложении функций
DROP TABLE IF EXISTS test;
CREATE TABLE test 
(
    id int GENERATED BY DEFAULT AS IDENTITY,
    c_text text
);

CREATE OR REPLACE FUNCTION test () RETURNS void
    LANGUAGE plpgsql
AS
$$
BEGIN
    DROP TABLE IF EXISTS test1;
    CREATE TEMP TABLE test1
    AS
    SELECT
        *
    FROM pg_query_stack();

    DROP TABLE IF EXISTS test2;
    CREATE TEMP TABLE test2
    AS
    SELECT
        *
    FROM pg_query_stack(0);

    INSERT INTO test
    (
        c_text
    )
    SELECT
        '666';

    DROP TABLE IF EXISTS test5;
    CREATE TEMP TABLE test5
    AS
    SELECT
        *
    FROM pg_query_stack(0);
END;
$$;

CREATE OR REPLACE FUNCTION test_up() RETURNS void
LANGUAGE plpgsql
AS
$$
BEGIN
    PERFORM test();
END;
$$;

SELECT test_up();

SELECT * FROM test1;

SELECT * FROM test2;

SELECT * FROM test;

SELECT * FROM test5;

DISCARD ALL;
DROP TABLE test;
DROP FUNCTION test();
DROP FUNCTION test_up();