-- Тест 010: Нагрузочный тест с циклом 1000 итераций
-- Этот тест проверяет стабильность работы расширения при интенсивной нагрузке
-- и отсутствие утечек памяти при многократных вызовах
DROP TABLE IF EXISTS test;
CREATE TABLE test 
(
    id int GENERATED BY DEFAULT AS IDENTITY,
    c_text text
);

CREATE OR REPLACE FUNCTION test () RETURNS void
    LANGUAGE plpgsql
AS
$$
BEGIN
    DROP TABLE IF EXISTS test1;
    CREATE TEMP TABLE test1
    AS
    SELECT
        *
    FROM pg_query_stack();

    DROP TABLE IF EXISTS test2;
    CREATE TEMP TABLE test2
    AS
    SELECT
        *
    FROM pg_query_stack(0);

    INSERT INTO test
    (
        c_text
    )
    SELECT
        '666';

    DROP TABLE IF EXISTS test5;
    CREATE TEMP TABLE test5
    AS
    SELECT
        *
    FROM pg_query_stack(0);
END;
$$;

CREATE OR REPLACE FUNCTION test_up() RETURNS void
LANGUAGE plpgsql
AS
$$
BEGIN
    PERFORM test();
END;
$$;

DO
$$
DECLARE
    _n int = 0;
BEGIN
    WHILE _n < 1000
    LOOP
        PERFORM test_up();
        _n = _n + 1;
    END LOOP;
END
$$ LANGUAGE plpgsql;

SELECT * FROM test1;

SELECT * FROM test2;

SELECT * FROM test;

SELECT * FROM test5;

DISCARD ALL;
DROP TABLE test;
DROP FUNCTION test();
DROP FUNCTION test_up();