-- Тест 011: Работа с триггерами
-- Этот тест проверяет корректность работы pg_query_stack в контексте триггеров
-- и каскадных операций с временными таблицами
DROP TABLE IF EXISTS test;
CREATE TABLE test
(
    id     int GENERATED BY DEFAULT AS IDENTITY,
    c_text text
);

DROP TABLE IF EXISTS test_dn;
CREATE TABLE test_dn
(
    id     int GENERATED BY DEFAULT AS IDENTITY,
    c_text text
);

CREATE OR REPLACE FUNCTION public.trigger_test () RETURNS trigger
    LANGUAGE plpgsql
AS
$$
BEGIN
    DROP TABLE IF EXISTS test1;
    CREATE TEMP TABLE test1
    AS
    SELECT
        *
    FROM pg_query_stack();

    INSERT INTO test_dn
    (
        c_text
    )
    SELECT
        c_text
    FROM inserted;

    RETURN NULL;
END;
$$;

CREATE FUNCTION public.trigger_test_dn () RETURNS trigger
    LANGUAGE plpgsql
AS
$$
BEGIN
    DROP TABLE IF EXISTS test2;
    CREATE TEMP TABLE test2
    AS
    SELECT
        *
    FROM pg_query_stack()
    UNION ALL 
    SELECT
        *
    FROM pg_query_stack(0);

    RETURN NULL;
END;
$$;

CREATE TRIGGER t1
    AFTER INSERT
    ON test
    REFERENCING new TABLE inserted
EXECUTE PROCEDURE public.trigger_test();

CREATE TRIGGER t2
    AFTER UPDATE
    ON test
    REFERENCING old TABLE deleted new TABLE inserted
EXECUTE PROCEDURE public.trigger_test();

CREATE TRIGGER t3
    AFTER INSERT
    ON test_dn
    REFERENCING new TABLE inserted
EXECUTE PROCEDURE public.trigger_test_dn();

INSERT INTO test
(
    c_text
)
SELECT
    '123';

SELECT * FROM test1;
SELECT * FROM test2;

DISCARD ALL;
DROP TABLE test;
DROP TABLE test_dn;
DROP FUNCTION public.trigger_test();
DROP FUNCTION public.trigger_test_dn();